config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/search' => 'wines#search'
  get '/results' => 'wines#results'
  get '/selection' => 'wines#selection'
  get '/show' => 'wines#show'

  resources :wines, except: [:edit, :update]

  resources :users do
    resources :favorites, only: [:create, :destroy]
  end

  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'



  get '/presentation' =>'wines#presentation'
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :wines, through: :favorites
  has_many :favorites

  # Add handlers to run when creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :first_name,
    presence: true,
    length: { maximum: 50 }

  validates :last_name,
    presence: true,
    length: { maximum: 50 }

  validates :age,
  numericality: { greater_than_or_equal_to: 21}

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # Secure password features:
  has_secure_password

  # Create a new remember token for a user:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token:
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def to_favorite(wine)
    binding.pry
    if wine.new_record?
      # Purchase.create(user_id: self.id, song_id: song.id)
      self.wines << wine
    end
  end

  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user=User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :age,
      :email,
      :password,
      :password_confirmation
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end

end

app/views/users/_user_form.html.erb
<div class="sign-up">
  <div class="col-lg-offset-7 col-lg-4 col-sm-3 col-sm-offset-6 sign_up" id="sign_up">
    <h1 class="form-title">Sign Up</h1>
  <% if @user.errors.any? %>
    <b>Errors:</b>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "Inhak", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "Kim", class: "form-control" %>
    </div>
    <div class="form-group" id="age">
      <%= f.label :age %>
      <%= f.select(:age, (21..100), :prompt => "Age", class: "form-control") %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, placeholder: "Inhakka@flakka.com", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "************", class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation, placeholder: "************", class: "form-control" %>
    </div>

    <div class="form-group" id="button">
      <%= f.submit "Submit", id: 'submit', type: "submit", class: "btn btn-default btn-custom btn-lg btn-primary center-block" %>
    </div>
  <% end %>
</div>

</div>

app/views/users/edit.html.erb
<h1>Edit <%= @user.first_name %></h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/new.html.erb
  <%= render "user_form" %>

app/views/users/show.html.erb
<div class="profile row">
  <div class="profile-list col-lg-offset-3 col-lg-6 col-sm-3 col-sm-offset-6 col-xs-10 col-xs-offset-1">
    <h1><%= @user.first_name%>  <%= @user.last_name %>'s Profile</h1>

      <p><%= @user.email %></p>

      <p><%= link_to "Edit", edit_user_path(@user) %></p>

    <h1 class="text-center">Favorite Wines</h1>

    <% current_user.wines.each do |wine| %>

      <div class="panel panel-default list-hover" style="margin-left: 15px; margin-right: 15px">
         <div class="panel-heading">
           <h3 class="panel-title"><%= link_to wine["name"], selection_path + "?&id=#{wine["snooth_id"]}&food=1" %></h3>
         <div class="panel-body">
           <div class="row">
             <div class="col-md-4">
              <a href="<%= selection_path + "?&id=#{wine["snooth_id"]}&food=1" %>"><img src="<%= wine["image_url"] %>" class="img-responsive"></a>
              </a>
             </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

</div>