config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/search' => 'wines#search'
  get '/results' => 'wines#results'
  get '/selection' => 'wines#selection'
  get '/show' => 'wines#show'

  resources :wines, except: [:edit, :update]

  resources :users do
    resources :favorites, only: [:create, :destroy]
  end

  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'



  get '/presentation' =>'wines#presentation'
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  has_many :favorites
  has_many :users, through: :favorites

  validates :name, presence: true
  validates :image_url, presence: true

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController

  def index
    @wines = Wine.all
  end

  def presentation
  end

  def show
    @stores = get_store_info(params[:z])
    @zip = params[:z]
  end

  def selection
    @wine = get_wine_info(params[:id])
  end

  def results
    if params[:q].downcase.include? 'inhak'
      redirect_to "http://youtu.be/F5O553ZOdRo"
    elsif params[:q].downcase.include? 'rick' || 'astley'
      redirect_to "http://youtu.be/dQw4w9WgXcQ"
    else
      @wines = get_wine_url(params[:q], params[:country], params[:color], params[:n], params[:xp], params[:mp], params[:sort])
        if @wines.blank?
          flash[:error] = 'No wines exist for your search parameters.'
          redirect_to search_path
        end
    end

  end

  private

  def get_wine_url(wine='wine', country='USA', color='', limit = 100,xp='', mp='', sort='')
    wine = wine.gsub(" ", "+") + "+" + country.gsub(" ", "+")
    if color == ''
      response = HTTParty.get("http://api.snooth.com/wines/?akey=#{SNOOTH_API}&t=wines&n=#{limit}&q=#{wine}&mp=#{mp}&xp=#{xp}&s=#{sort}")
    else
      response = HTTParty.get("http://api.snooth.com/wines/?akey=#{SNOOTH_API}&t=wines&n=#{limit}&q=#{wine}&color=#{color}&mp=#{mp}&xp=#{xp}&s=#{sort}")
    end
    response_hash = JSON(response)
    response_hash["wines"]
  end

  def get_wine_info(name)
    name = name.gsub(" ", "+")
    response = HTTParty.get("http://api.snooth.com/wine/?akey=#{SNOOTH_API}&photos=1&food=1&id=#{name}")
    response_hash = JSON(response)
    response_hash["wines"]
  end

  def get_store_info(zip)
    response = HTTParty.get("http://api.snooth.com/stores/?akey=#{SNOOTH_API}&c=US&z=#{zip}")
    response_hash = JSON(response)
    response_hash["stores"]
  end
end

app/views/wines/index.html.erb
<h1>Wines Favorited</h1>

  <% @wines.each do |wine| %>

    <p><%= wine.name %></p>
    <p>Price: $<%=wine.price%></p>
    <p>Rating: <%=wine.rating%></p>
    <p>Review: <%=wine.review%></p>
    <img src = "<%= wine.image_url %>">

    <%= form_for song, method: 'delete' do |f| %>
    <%= f.submit 'Remove Wine', id: 'delete-wine-#{wine.id}' %>
  <% end %>
<% end %>

app/views/wines/presentation.html.erb
<div class="presentation">
  <div class="presentation">
    <h1>Project 1 Overview</h1>

    <h3>What am I most Proud of?</h3>
      <ul>
        <li type=circle> How Meta this.</li>
        <li type=circle> Beginning to end.</li>
        <li type=circle> <i>T<b>ac</i>kl</b>ing <span class="big">my</span> <span class="scary">CSS</span> fear.</li>
      </ul>
    <h3>What was the biggest difficulty I ran into?</h3>
      <ul>
        <li type=circle> Internally before beginning? - <span class="scary">CSS</span></li>
        <li type=circle> API-Snooth</li>
        <li type=circle> Persistence</li>
      </ul>
    <h3>What would I do differently if I had to start over?</h3>
      <ul>
        <li type=circle> More 'market research'</li>
        <li type=circle> More API research</li>
        <li type=circle> More structured approach to <span class="scary">CSS</span></li>
      </ul>
  </div>
</div>

app/views/wines/results.html.erb
<div class="results row">
  <div class="result-list col-lg-offset-3 col-lg-6 col-sm-3 col-sm-offset-6 col-xs-10 col-xs-offset-1">
    <h1 class="text-center ">lovely libations</h1>

    <% @wines.each do |wine| %>
      <a href="<%= selection_path + "?&id=#{wine['code']}&food=1" %>">
      <div class="panel panel-default list-hover" style="margin-left: 15px; margin-right: 15px">
         <div class="panel-heading">
           <h3 class="panel-title"><%= link_to wine['name'], selection_path + "?&id=#{wine['code']}&food=1" %><span class="pull-right price">Price</span></h3>
         </div>
         <div class="panel-body">
           <div class="row">
             <div class="col-md-2">
               <a href="<%= selection_path + "?&id=#{wine['code']}&food=1" %>"><img src="<%= wine["image"] %>" class="img-rounded img-responsive" style="width: 100px; height: 100px">
              </a>
             </div>
             <div class="col-md-8">
              <p><strong>Varietal:</strong> <%= wine["varietal"] %></br></p>
              <p><strong>Region:</strong> <%= wine["region"] %></p>
             </div>
             <div class="col-md-2 pull-right price">
               <%= wine["price"] %>
           </div>
         </div>
        </div>
      </div>
    </a>
    <% end %>

  </div>
</div>

app/views/wines/search.html.erb
<div class="search row" role="form">
  <div class="col-lg-offset-7 col-lg-4 col-sm-3 col-sm-offset-6" id="sign_up">
    <h1 class="form-title">Search for a Wine:</h1>
  <% flash.each do |name, msg| %>
    <%= content_tag :p, msg, class: name %>
  <% end %>

  <%= form_tag("/results", method: "get") do %>
    <div class="form-group">
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q, nil, placeholder: "Ex. Merlot, Pinot Noir", class: "form-control") %>
    </div>
    <div class="form-group">
        <%= label_tag(:country, "Country") %>
        <%= select_tag(:country, options_for_select(supported_countries), :prompt => "Select Country", class: "form-control") %>
    </div>
    <div class="form-group">
        <%= label_tag(:n, 'Limit Search:') %>
        <%= select_tag(:n, options_for_select(1..100, 25), class: "form-control")%>
    </div>
    <div class="form-group">
        <%= label_tag(:color, "Color:") %>
        <%= select_tag(:color, options_for_select(['red', 'white', 'rose', 'amber', 'clear']), :prompt => 'Select Color', class: "form-control") %>
    </div>
    <div class="form-group">
        <%= label_tag(:mp, "Min Price:") %>
        <%= text_field_tag(:mp,nil, class: "form-control") %>
    </div>
    <div class="form-group">
        <%= label_tag(:xp, "Max Price:") %>
        <%= text_field_tag(:xp, nil,class: "form-control") %>
    </div>
    <div class="form-group">
        <%= label_tag(:sort, "Sort by:") %>
        <%= select_tag(:sort, options_for_select(sort_options), :prompt => "Sort by", class: "form-control") %>
    </div>
    <div class="form-group" id="button">
        <%= submit_tag("Search", class: "btn btn-default btn-custom btn-lg btn-primary center-block") %>
    </div>
    <% end %>
    </div>
</div>

app/views/wines/selection.html.erb
<div class="selection row">
  <div class="selection-list col-lg-offset-3 col-lg-6 col-sm-3 col-sm-offset-6 col-xs-10 col-xs-offset-1">
    <% @wine.each do |wine| %>
      <div class="selection-title">
        <h1><%= wine["name"] %></h1>
          <h3><strong>Region</strong>: <%= wine["region"] %></h3>
      </div>
    <div class="header">
      <div class="selection-info">
        <img src="<%= wine["image"] %>" class="col-xs-4 img-rounded img-responsive">
        <p><strong>Vintage</strong>: <%= wine["vintage"]%></p>
        <p><strong>Varietal:</strong>: <%= wine["varietal"] %></p>
          <% if wine["sugar"] != '' %>
        <P class="bold"><strong>Attributes of Wine</strong></p>
          <p>
           <strong>Sugar:</strong> <%= wine["sugar"] %>g/l
           <strong>Alcohol:</strong> <%= wine["alcohol"] %>%
           <strong>pH:</strong> <%= wine["ph"] %>
           <strong>TA:(total acidity):</strong> <%= wine["acidity"] %>
          </p>
          <% end %>
          <% if wine["wm_notes"] != '' %>
        <p class="selection-info"><strong>Wine Maker's Notes</strong>: <%= wine["wm_notes"] %></p>
          <% end %>
      </div>
    </div>

    <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
            <strong>Reviews</strong>
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in">
        <div class="panel-div">
          <% wine["reviews"].each do |review|%>
          <% if review["body"] != '' %>
          <h5><strong><%= review["name"] %></strong></h5>
          <p><%= review["body"] %></p>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          <strong>Recipes</strong>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-div">
        <% wine["recipes"].each do |recipe|%>
          <div class="col-xs-6 col-md-4 thumbnail-list">
            <a href="<%= recipe["source_link"] %>" class="thumbnail image-w" data-toggle="tooltip" data-placement="top" title="<%= recipe["name"]%>">
              <img src="<%= recipe["image"] %>" class = "img-responsive" alt="...">
              <div class="cover">
                <p><%=recipe["name"] %></p>
              </div>
            </a>
          </div>

        <% end %>
        </div>
      </div>
    </div>
</div>

      <%= form_tag("/show", :method => 'get') do%>
        <p>
        <%= hidden_field_tag(:id, wine["code"]) %>
        <%= label_tag(:z, "Search Zip Codes:") %>
        <%= text_field_tag(:z, nil, placeholder: "Ex. 20001") %>
        <%= submit_tag 'Search' %>
        </p>
      <% end %>

      <% if signed_in? %>
      <%= form_tag user_favorites_path(@current_user) do %>

        <%= hidden_field wine["wine_code"], "snooth_id", value: wine["code"]  %>
        <%= hidden_field wine["wine_code"], "name", value: wine["name"]  %>
        <%= hidden_field wine["wine_code"], "region", value: wine["region"]  %>
        <%= hidden_field wine["wine_code"], "image_url", value: wine["image"]  %>

        <%= submit_tag 'Favorite' %>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/wines/show.html.erb
<div class="address row">
  <div class="address-list col-lg-offset-3 col-lg-6 col-sm-3 col-sm-offset-6 col-sm-10 col-xs-offset-1">
    <h1 class="text-center">Where to Buy Near <%= @zip %></h1>
    <% @stores.first(10).each do |store| %>

      <div class="panel panel-default" style="margin-left: 15px; margin-right: 15px">
        <div class="panel-heading">
          <h3 class="panel-title"><h3><%= store["name"] %></h3></h3>
        </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-8">
                <address>
                  <%= store["address"] %>
                  <%= store["city"] %>, <%= store["state"] %>
                  <%= store["number"] %>
                </address>
                <a href="<%=store["url"]%>">Website</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

</div>