config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/search' => 'wines#search'
  get '/results' => 'wines#results'
  get '/selection' => 'wines#selection'
  get '/show' => 'wines#show'

  resources :wines, except: [:edit, :update]

  resources :users do
    resources :favorites, only: [:create, :destroy]
  end

  resources :sessions, only: [:create]

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'



  get '/presentation' =>'wines#presentation'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wine-OH!</title>

<link rel="shortcut icon" href="/favicon.ico">

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Creepster' rel='stylesheet' type='text/css'>
  <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Lilita+One|Cabin+Sketch|Fugaz+One|Salsa'>
  <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Comfortaa'>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script name="text/javascript" src="assets/javascripts/application.js"></script>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Wine-OH!</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
          <li class="active"><%= link_to "My Wines", user_path(current_user) %></li>
          <% end %>
        <li><%= link_to "Search", search_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign-in", signin_path %></li>
        <li><%= link_to "Sign-up", signup_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

      <%= yield %>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>